targetSystemId: ETRM1

quarkus:
  http:
    port: 8081

mp:
  messaging:
    incoming:
      legal-entity-in:
        connector: smallrye-kafka
        auto:
          offset:
            reset: "earliest"
        topic: "legal-entity"
      legal-entity-reprocess:
        connector: smallrye-kafka
        topic: "legal-entity"
        value:
          deserializer: "org.ksetl.demo.LegalEntitySourceDeserializer"
        max:
          poll:
            records: 1
        auto:
          offset:
            reset: "earliest"
      message-processing-error-metadata-in:
        connector: smallrye-kafka
        topic: "message-processing-error-metadata"
        value:
          deserializer: org.ksetl.demo.MessageProcessingErrorMetadataDeserializer
    outgoing:
      legal-entity-out:
        connector: smallrye-kafka
        topic: "legal-entity-etrm1"
        key:
          serializer: org.apache.kafka.common.serialization.IntegerSerializer
      message-processing-error-metadata-out:
        connector: smallrye-kafka
        topic: "message-processing-error-metadata"

